# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d682ced6c05b0092375469144f7df2a70b4493722dc652eb26b0b9b0a093643a0a764e48d7189d38bd475ac50f6345036e9b416ab456609a3a11f6b2afa2c220

test:
  secret_key_base: ff3847d14093626df93b0c14cfc73f65e6e4cb40f2f2fb89fbefdbd0e1aed84d87544ed9fc3dc861c3856cb7b7da6e2a5071e9b035f433a7acbc513ef3528cdb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
